---
name: Github Pages Deploy
run-name: ${{ github.actor }} is compiling to Pages
on: [push]
jobs:
  build_vue:
    name: Build Vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: mattly/VuePagesAction@1.0.4
        with:
          username: mattly
          reponame: admin-prototypes
          token: ${{ secrets.GITHUB_TOKEN }}
